
import type { ComboboxOption } from '@/components/ui/combobox';
import type { User } from './types';

// This file should ONLY contain static data arrays.
// No functions, no complex imports.

export const users = [
    { id: 'admin-00', name: 'Admin User', email: 'admin@admin2023.com', avatarUrl: 'https://placehold.co/100x100.png', role: 'Sub-Directorate Head', isApproved: true },
    { id: 'admin-01', name: 'Hakim Alif Rahman', email: 'hakimalifrahman@gmail.com', avatarUrl: 'https://lh3.googleusercontent.com/a/ACg8ocL-Xb1W-9733aG4ttD2Qp2i54s1g7T6lS7-_h2Y4d-3pA=s96-c', role: 'Sub-Directorate Head', isApproved: true },
    { id: '8aOs7OSaL8XFXLq7DxzbnuXN5eC3', name: 'Chewy Sihusky', email: 'chewysihusky@gmail.com', avatarUrl: 'https://placehold.co/100x100.png', role: 'Sub-Directorate Head' },
    { id: 'rizkywirapratama434', name: 'Rizky Wirapratama', email: 'rizkywirapratama434@gmail.com', avatarUrl: 'https://placehold.co/100x100.png', role: 'Sub-Directorate Head', isApproved: true },
    { id: 'user-1', name: 'Alex Johnson', email: 'alex.johnson@example.com', avatarUrl: 'https://placehold.co/100x100.png', role: 'Team Lead' },
    { id: 'user-2', name: 'Maria Garcia', email: 'maria.garcia@example.com', avatarUrl: 'https://placehold.co/100x100.png', role: 'PIC' },
    { id: 'user-3', name: 'James Smith', email: 'james.smith@example.com', avatarUrl: 'https://placehold.co/100x100.png', role: 'PIC Assistant' },
    { id: 'user-4', name: 'Patricia Williams', email: 'patricia.williams@example.com', avatarUrl: 'https://placehold.co/100x100.png', role: 'Functional' },
];

export const userDepartments: User['department'][] = [
    'Pegawai STD', 'PEL', 'AIR', 'SPU', 'OPS', 'DGCA', 'K/L lain'
];

export const rulemakingTaskOptions: ComboboxOption[] = [
    { value: 'Gap Analysis', label: 'Gap Analysis' },
    { value: 'Penyusunan Draft', label: 'Penyusunan Draft' },
    { value: 'Diskusi dengan SME', label: 'Diskusi dengan SME' },
    { value: 'Diskusi dengan Stakeholder', label: 'Diskusi dengan Stakeholder' },
    { value: 'Penyusunan KP/PM', label: 'Penyusunan KP/PM' },
    { value: 'Persetujuan Manajemen', label: 'Persetujuan Manajemen' },
    { value: 'Evaluasi Bagkum', label: 'Evaluasi Bagkum' },
    { value: 'Revisi oleh Direktorat hasil koreksi Bagkum record keeping dan sinkronisasi', label: 'Revisi oleh Direktorat hasil koreksi Bagkum record keeping dan sinkronisasi' },
    { value: 'Finalisasi oleh Bagkum', label: 'Finalisasi oleh Bagkum' },
    { value: 'Evaluasi oleh Biro Hukum', label: 'Evaluasi oleh Biro Hukum' },
    { value: 'Evaluasi oleh Kumham', label: 'Evaluasi oleh Kumham' },
    { value: 'Setneg dan Pengesahan', label: 'Setneg dan Pengesahan' },
    { value: 'Sosialisasi oleh Direktorat', label: 'Sosialisasi oleh Direktorat' },
];

export const timKerjaTaskOptions: ComboboxOption[] = [
    { value: 'Initial Planning', label: 'Initial Planning' },
    { value: 'Requirement Gathering', label: 'Requirement Gathering' },
    { value: 'Design Phase', label: 'Design Phase' },
    { value: 'Development Sprint 1', label: 'Development Sprint 1' },
    { value: 'Development Sprint 2', label: 'Development Sprint 2' },
    { value: 'Testing & QA', label: 'Testing & QA' },
    { value: 'User Acceptance Testing (UAT)', label: 'User Acceptance Testing (UAT)' },
    { value: 'Deployment', label: 'Deployment' },
    { value: 'Post-launch Support', label: 'Post-launch Support' },
];

export const indonesianAircraftTypes: ComboboxOption[] = [
    { value: 'Airbus A320', label: 'Airbus A320' },
    { value: 'Airbus A321', label: 'Airbus A321' },
    { value: 'Airbus A330', label: 'Airbus A330' },
    { value: 'ATR 72', label: 'ATR 72' },
    { value: 'Bell 206', label: 'Bell 206' },
    { value: 'Bell 412', label: 'Bell 412' },
    { value: 'Bell 505', label: 'Bell 505' },
    { value: 'Boeing 737', label: 'Boeing 737' },
    { value: 'Boeing 737-300F', label: 'Boeing 737-300F' },
    { value: 'Boeing 737-800', label: 'Boeing 737-800' },
    { value: 'Boeing 737-900ER', label: 'Boeing 737-900ER' },
    { value: 'Boeing 777', label: 'Boeing 777' },
    { value: 'Bombardier CRJ1000', label: 'Bombardier CRJ1000' },
    { value: 'Cessna C172', label: 'Cessna C172' },
    { value: 'Cessna C208B - Grand Caravan', label: 'Cessna C208B - Grand Caravan' },
    { value: 'DHC-6 Twin Otter', label: 'DHC-6 Twin Otter' },
    { value: 'Eurocopter AS350', label: 'Eurocopter AS350' },
    { value: 'Eurocopter EC135P2', label: 'Eurocopter EC135P2' },
    { value: 'PAC 750XL', label: 'PAC 750XL' },
    { value: 'Pilatus PC-6 Porter', label: 'Pilatus PC-6 Porter' },
    { value: 'Robinson R44', label: 'Robinson R44' },
    { value: 'Robinson R66', label: 'Robinson R66' },
    { value: 'Thrush S2R-T34', label: 'Thrush S2R-T34' },
];

export const aocOptions: ComboboxOption[] = [
    { value: 'SMART CAKRAWALA AVIATION - 135', label: 'SMART CAKRAWALA AVIATION - 135' },
    { value: 'SEMUWA AVIASI MANDIRI - 135', label: 'SEMUWA AVIASI MANDIRI - 135' },
    { value: 'ALTIUS BAHARI INDONESIA - 135', label: 'ALTIUS BAHARI INDONESIA - 135' },
    { value: 'BALAI BESAR KALIBRASI FASILITAS PENERBANGAN - 135', label: 'BALAI BESAR KALIBRASI FASILITAS PENERBANGAN - 135' },
    { value: 'RIMBUN ABADI AVIASI - 135', label: 'RIMBUN ABADI AVIASI - 135' },
    { value: 'REVEN GLOBAL AIRTRANSPORT - 135', label: 'REVEN GLOBAL AIRTRANSPORT - 135' },
    { value: 'JET EKSEKUTIF TRAVYA - 135', label: 'JET EKSEKUTIF TRAVYA - 135' },
    { value: 'VOLTA PASIFIK AVIASI - 135', label: 'VOLTA PASIFIK AVIASI - 135' },
    { value: 'AIRFAST INDONESIA - 135', label: 'AIRFAST INDONESIA - 135' },
    { value: 'SAYAP GARUDA INDAH - 135', label: 'SAYAP GARUDA INDAH - 135' },
    { value: 'ASIAN ONE AIR - 135', label: 'ASIAN ONE AIR - 135' },
    { value: 'TRAVIRA AIR - 135', label: 'TRAVIRA AIR - 135' },
    { value: 'DERAZONA AIR SERVICE - 135', label: 'DERAZONA AIR SERVICE - 135' },
    { value: 'NATIONAL UTILITY HELICOPTER - 135', label: 'NATIONAL UTILITY HELICOPTER - 135' },
    { value: 'INTAN ANGKASA AIR SERVICE - 135', label: 'INTAN ANGKASA AIR SERVICE - 135' },
    { value: 'AIR PASIFIC UTAMA - 135', label: 'AIR PASIFIC UTAMA - 135' },
    { value: 'PURAWISATA BARUNA - 135', label: 'PURAWISATA BARUNA - 135' },
    { value: 'PENERBANGAN ANGKASA SEMESTA - 135', label: 'PENERBANGAN ANGKASA SEMESTA - 135' },
    { value: 'ASI PUDJIASTUTI AVIATION - 135', label: 'ASI PUDJIASTUTI AVIATION - 135' },
    { value: 'DABI AIR NUSANTARA - 135', label: 'DABI AIR NUSANTARA - 135' },
    { value: 'EKSPRES TRANS ANTARBENUA - 135', label: 'EKSPRES TRANS ANTARBENUA - 135' },
    { value: 'PEGASUS AIR SERVICES - 135', label: 'PEGASUS AIR SERVICES - 135' },
    { value: 'TRI MG AIRLINES - 135', label: 'TRI MG AIRLINES - 135' },
    { value: 'EASTINDO - 135', label: 'EASTINDO - 135' },
    { value: 'JHONLIN AIR TRANSPORT - 135', label: 'JHONLIN AIR TRANSPORT - 135' },
    { value: 'SURYA AIR - 135', label: 'SURYA AIR - 135' },
    { value: 'ERSA EASTERN AVIATION - 135', label: 'ERSA EASTERN AVIATION - 135' },
    { value: 'MATTHEW AIR NUSANTARA - 135', label: 'MATTHEW AIR NUSANTARA - 135' },
    { value: 'MARTA BUANA ABADI - 135', label: 'MARTA BUANA ABADI - 135' },
    { value: 'ANGKASA SUPER SERVICES - 135', label: 'ANGKASA SUPER SERVICES - 135' },
    { value: 'KOMALA INDONESIA - 135', label: 'KOMALA INDONESIA - 135' },
    { value: 'ELANG LINTAS INDONESIA - 135', label: 'ELANG LINTAS INDONESIA - 135' },
    { value: 'ELANG NUSANTARA AIR - 135', label: 'ELANG NUSANTARA AIR - 135' },
    { value: 'AMA - 135', label: 'AMA - 135' },
    { value: 'ALDA TRANS PAPUA - 135', label: 'ALDA TRANS PAPUA - 135' },
    { value: 'SPIRIT AVIA SENTOSA - 135', label: 'SPIRIT AVIA SENTOSA - 135' },
    { value: 'WESTSTAR AVIATION INDONESIA - 135', label: 'WESTSTAR AVIATION INDONESIA - 135' },
    { value: 'WHITESKY AVIATION - 135', label: 'WHITESKY AVIATION - 135' },
    { value: 'CARPEDIEM AVIASI MANDIRI - 135', label: 'CARPEDIEM AVIASI MANDIRI - 135' },
    { value: 'WISARADA SAPANTA UTAMA - 135', label: 'WISARADA SAPANTA UTAMA - 135' },
    { value: 'GENESA DIRGANTARA - 135', label: 'GENESA DIRGANTARA - 135' },
    { value: 'NATIONAL GLOBAL AVIASI - 135', label: 'NATIONAL GLOBAL AVIASI - 135' },
    { value: 'TRANSWISATA PRIMA AVIATION - 135', label: 'TRANSWISATA PRIMA AVIATION - 135' },
    { value: 'ZAVERYNA UTAMA - 135', label: 'ZAVERYNA UTAMA - 135' },
    { value: 'ABADI MEGA ANGKUTAN NUSANTARA - 135', label: 'ABADI MEGA ANGKUTAN NUSANTARA - 135' },
    { value: 'VAST INTRA AVIA - 135', label: 'VAST INTRA AVIA - 135' },
    { value: 'IKAIROS AIR SERVICES - 135', label: 'IKAIROS AIR SERVICES - 135' },
    { value: 'INDONESIA TRANSPORT & INFRASTRUKTUR - 121', label: 'INDONESIA TRANSPORT & INFRASTRUKTUR - 121' },
    { value: 'SUPER AIR JET - 121', label: 'SUPER AIR JET - 121' },
    { value: 'MY INDO - 121', label: 'MY INDO - 121' },
    { value: 'GARUDA INDONESIA - 121', label: 'GARUDA INDONESIA - 121' },
    { value: 'TRIGANA AIR SERVICE - 121', label: 'TRIGANA AIR SERVICE - 121' },
    { value: 'PELITA AIR SERVICE - 121', label: 'PELITA AIR SERVICE - 121' },
    { value: 'INDONESIA AIR ASIA - 121', label: 'INDONESIA AIR ASIA - 121' },
    { value: 'LION MENTARI AIRLINES - 121', label: 'LION MENTARI AIRLINES - 121' },
    { value: 'WINGS ABADI AIRLINES - 121', label: 'WINGS ABADI AIRLINES - 121' },
    { value: 'TRI MG AIRLINES - 121', label: 'TRI MG AIRLINES - 121' },
    { value: 'SRIWIJAYA AIR - 121', label: 'SRIWIJAYA AIR - 121' },
    { value: 'JAYAWIJAYA DIRGANTARA - 121', label: 'JAYAWIJAYA DIRGANTARA - 121' },
    { value: 'CITILINK INDONESIA - 121', label: 'CITILINK INDONESIA - 121' },
    { value: 'BATIK AIR INDONESIA - 121', label: 'BATIK AIR INDONESIA - 121' },
    { value: 'NAM AIR - 121', label: 'NAM AIR - 121' },
    { value: 'BLACK STONE AIRLINE - 121', label: 'BLACK STONE AIRLINE - 121' },
    { value: 'PT POMPA AIR - 121', label: 'PT POMPA AIR - 121' },
    { value: 'CARDIG AIR - 121', label: 'CARDIG AIR - 121' },
    { value: 'TRANSNUSA AVIATION MANDIRI - 121', label: 'TRANSNUSA AVIATION MANDIRI - 121' },
    { value: 'PT. EXPRESS CARGO AIRLINES - 121', label: 'PT. EXPRESS CARGO AIRLINES - 121' },
    { value: 'BBN AIRLINES INDONESIA - 121', label: 'BBN AIRLINES INDONESIA - 121' },
    { value: 'PT. RUSKY AERO INDONESIA - 121', label: 'PT. RUSKY AERO INDONESIA - 121' },
    { value: 'ABADI MEGA ANGKUTAN NUSANTARA - 121', label: 'ABADI MEGA ANGKUTAN NUSANTARA - 121' },
    { value: 'VAST INTRA AVIA - 121', label: 'VAST INTRA AVIA - 121' },
    { value: 'PERSADA PERKASA AIRNESIA - 121', label: 'PERSADA PERKASA AIRNESIA - 121' },
];

export const taxonomyOptions: ComboboxOption[] = [
    { value: 'Turbulence Encounter (TURB)', label: 'Turbulence Encounter (TURB)' },
    { value: 'System/Component Failure or Malfunction (Powerplant) (SCF-PP)', label: 'System/Component Failure or Malfunction (Powerplant) (SCF-PP)' },
    { value: 'Loss of Control Inflight (LOC-I)', label: 'Loss of Control Inflight (LOC-I)' },
    { value: 'Abnormal Runway Contact (ARC)', label: 'Abnormal Runway Contact (ARC)' },
    { value: 'Runway Excursion (RE)', label: 'Runway Excursion (RE)' },
    { value: 'ATM/CNS (ATM)', label: 'ATM/CNS (ATM)' },
    { value: 'Fuel Related (FUEL)', label: 'Fuel Related (FUEL)' },
    { value: 'System/Component Failure – Non-Powerplant (SCF-NP)', label: 'System/Component Failure – Non-Powerplant (SCF-NP)' },
    { value: 'Belum tertaxonomy', label: 'Belum tertaxonomy' },
];

    
